trigger:
  - "*"

parameters:
  - name: salt
    default: 'auth'

variables:
  - template: variables.yml

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: terraform.yml
    parameters:
      terraformVersion: $(terraformVersion)
      terraformPath: $(terraformPath)
      servicePrinciple: $(servicePrinciple)
      containerName: $(terraformContainerName)
      storageAccountName: $(terraformStorageAccountName)
      workspace: ${{ parameters.salt }}
      resourceGroupName: $(terraformResourceGroupName)
      env:
        TF_VAR_branch: ${{ parameters.salt }}
