trigger:
  - "*"

parameters:
  - name: salt
    default: 'auth'
  - name: useWorkspace
    default: true
    type: boolean

variables:
  - template: variables.yml
  - name: saltVar
    ${{ if eq(parameters.useWorkspace, true) }}:
      value: ${{ parameters.salt }}
    ${{ else }}:
      value: ''

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: terraform.yml
    parameters:
      terraformVersion: $(terraformVersion)
      terraformPath: $(terraformPath)
      servicePrinciple: $(servicePrinciple)
      containerName: $(terraformContainerName)
      storageAccountName: $(terraformStorageAccountName)
      workspace: ${{ parameters.salt }}
      resourceGroupName: $(terraformResourceGroupName)
      env:
        TF_VAR_branch: ${{ variables.saltVar }}
