trigger:
  - "*"

parameters:
  - name: salt
    default: ''
  - name: useWorkspace
    default: false
    type: boolean

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: terraform.yml
    parameters:
      terraformVersion: 1.3.6
      terraformPath: terraform
      servicePrinciple: MCAPS-Hybrid-REQ-49645-2022-jasojohnson
      containerName: terraform
      storageAccountName: samobitf
      workspace: ${{ parameters.salt }}
      useWorkspace: ${{ parameters.useWorkspace }}
      resourceGroupName: terraformstate-rg
      env:
        TF_VAR_branch: ${{ parameters.salt }}
